# Generated by Django 5.0.6 on 2024-06-23 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jjapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="teachersubjectassignment",
            name="is_class_teacher",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name="teachersubjectassignment",
            unique_together={("teacher", "subject", "grade")},
        ),
    ]
